### ISSUE TITLE
مشکل هنگام لود کردن تقویم در دیالوگ فرگمنت

### ISSUE THREAD

**Issue by SirLordPouya** [Roojin/persian-calendar-view#13]
سلام
وقتی تقویم رو در دیالوگ فرگمنت لود میکنم اپ کرش میکنه.
لاگ کت : 
```
 Caused by: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.support.v7.app.AppCompatActivity
 at ir.mirrajabi.persiancalendar.PersianCalendarView.makeView(PersianCalendarView.java:102)
  at ir.mirrajabi.persiancalendar.PersianCalendarView.<init>(PersianCalendarView.java:35)

```

**Comment by mirrajabi** [comment]
سلام
اکتیویتی ای که توش این ویو رو گذاشتی کدومه؟
android.support.v7.app.AppCompatActivity
یا
android.app.Activity

**Comment by SirLordPouya** [comment]
. هست AppCompatActivity اکتیویتی که از توش دیالوگ فرگمنتم رو کال میکنم

**Comment by SirLordPouya** [comment]
من دیالوگ فرگمنتم رو تبدیل کردم به دیالوگ اکتیویتی و مشکل رفع شد. فکر کنم مشکل از لود شدن فرگمنت های لایبراری توی یه فرگمنت دیگه باشه.

**Comment by mirrajabi** [comment]
فک کنم متوجه شدم مشکل از کجاست ولی ممکنه یه مقدار طول بکشه تا وقت کنم فیکسش کنم.

**Comment by mirrajabi** [comment]
> من دیالوگ فرگمنتم رو تبدیل کردم به دیالوگ اکتیویتی و مشکل رفع شد. فکر کنم مشکل از لود شدن فرگمنت های لایبراری توی یه فرگمنت دیگه باشه.
 
اکتیویتی رو نتونه از توی کانتکست بکشه بیرون میره تو دیوار

**Comment by SirLordPouya** [comment]
من اینو تست کردم، ولی بعدش ویو رو پیدا نمیکرد.
    else if (cont instanceof AppCompatActivity)
       m =  (AppCompatActivity)...;
    else if (cont instanceof ContextWrapper)
        m = (((ContextWrapper)cont).getBaseContext());

**Comment by vahidarr** [comment]
دوست عزیز منم از فرگمنت میخوام توی دیالوگ تقویم رو نشون بدم  اینو میگه:
`No view found for id 0x7f080055 (com.example.vahid.preinvoice:id/fragment_holder) for fragment CalendarFragment`

**Comment by abbasnaqdi** [comment]
داخل `BottomSheetDialogFragment` هم این مشکل وجود داره
```
اگر فقط عرض و طول ست کنم
androidx.appcompat.view.ContextThemeWrapper 
cannot be cast to androidx.appcompat.app.AppCompatActivity

اگر رنگ یا تنظیم دیگه ای ست کنم
Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
```
با `فرگمنت` تست کردم مشکلی نداره.
