### ISSUE TITLE
مشکل نمایش تقویم در دیالوگ

### ISSUE THREAD

**Issue by hossein-rezaeian** [Roojin/persian-calendar-view#7]
سلام وقتی که داخل دیالوگ میخوام این تقویم رو نمایش بدم و با برنامه کرش میکنه با اینفلیتر اون لایه رو مه تقویم داخلش قرار داره رو میخوام به ویو تبدیل کنم کرش میکنه

**Comment by mirrajabi** [comment]
سلام
لاگ کرش رو همینجا کپی کن

**Comment by hossein-rezaeian** [comment]
10-30 15:44:51.347 2736-2736/com.resef.app.residemenu E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        java.lang.IllegalArgumentException: No view found for id 0x7f0900d7 (com.resef.app.residemenu:id/fragment_holder) for fragment CalendarFragment{426d9dc0 #3 id=0x7f0900d7 ir.mirrajabi.persiancalendar.core.fragments.CalendarFragment}
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1293)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                            at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                            at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                            at android.os.Handler.handleCallback(Handler.java:730)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                            at android.os.Looper.loop(Looper.java:177)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5493)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:525)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
                                                                            at dalvik.system.NativeStart.main(Native Method)
این لاگ کرش اینم دستوری که دارم استفاده میکنم
` View v =  inflater.inflate(R.layout.dialog_time_freighter, null, false);`
اینم کد های فایل xml
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    android:id="@+id/aaaa"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    >
    <ir.mirrajabi.persiancalendar.PersianCalendarView
        android:id="@+id/persian_calendar"
        android:layout_width="match_parent"
        android:layout_height="290sp"
        app:pcv_colorBackground="#292929"
        app:pcv_colorDayName="#bab6b6"
        app:pcv_colorHoliday="#ffd506"
        app:pcv_colorHolidaySelected="#f1f2f3"
        app:pcv_colorNormalDaySelected="#d9d9d9"
        app:pcv_colorNormalDay="#f3f4f5"
        app:pcv_eventUnderlineColor="#02f0f0"/>
</LinearLayout>
```

**Comment by mirrajabi** [comment]
در اسرع وقت چک میکنم @hossein-rezaeian 
مطمئنی که مشکل از کتابخونست؟
یکی از بچه ها مشکلش این بود که از چند تا لایبرری تقویم استفاده میکرد و از قضا اسم دو تا لیوت متفاوت توی دو تا از کتابخونه ها یکی بود و باعث میشد که اشتباهی اینفلیت شه و این داستان پیش بیاد.

**Comment by hossein-rezaeian** [comment]
آها درسته این هم امکانش هست من داخل یه پروژه خالی چک میکنم خبر میدم

**Comment by mirrajabi** [comment]
@hossein-rezaeian نتیجه ای حاصل شد؟

**Comment by mirrajabi** [comment]
Closing due to inactivity.
Reopen if you're sure this problem is caused by the library
