### ISSUE TITLE
مشکل استفاده از تقویم داخل فرگمنت

### ISSUE THREAD

**Issue by MansoorJafari** [Roojin/persian-calendar-view#9]
سلام 
ببخشید زمانی که تقویم رو داخل فرگمنت میذارم و فرگمنت رو اجرا میکنم با این خطا مواجه میشم

`android.view.InflateException: Binary XML file line #8: Error inflating class ir.mirrajabi.persiancalendar.PersianCalendarView`

xml فرگمنتم هم اینشکلیه

```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context="com.track.mansoorjafari.tracking.fragments.persianCalendar_fragment">

    <ir.mirrajabi.persiancalendar.PersianCalendarView
        android:id="@+id/persian_calendar"
        android:layout_width="match_parent"
        android:layout_height="300dp"
        app:pcv_colorBackground="#292929"
        app:pcv_colorDayName="#bab6b6"
        app:pcv_colorHoliday="#ffd506"
        app:pcv_colorHolidaySelected="#f1f2f3"
        app:pcv_colorNormalDaySelected="#d9d9d9"
        app:pcv_colorNormalDay="#f3f4f5"
        app:pcv_eventUnderlineColor="#02f0f0"/>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_persian_calendar"
        android:layout_width="match_parent"
        android:layout_marginTop="300dp"
        android:layout_height="match_parent"/>

</RelativeLayout>
```

داخل اکتیوتی استفاده کردم بدون مشکل کار کرد.
ولی داخل فرگمنت مشکل داره

**Comment by mirrajabi** [comment]
کل لاگ خطا رو کپی کن لطفا. نه فقط خط اولش.

**Comment by MansoorJafari** [comment]
بفرماید


android.view.InflateException: Binary XML file line #8: Error inflating class ir.mirrajabi.persiancalendar.PersianCalendarView
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:621)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                    at com.track.mansoorjafari.tracking.fragments.persianCalendar_fragment.onCreateView(persianCalendar_fragment.java:54)
                                                                                    at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                                    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                                    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                                    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                                    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                                    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                                    at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:595)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                    at com.track.mansoorjafari.tracking.fragments.persianCalendar_fragment.onCreateView(persianCalendar_fragment.java:54) 
                                                                                    at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809) 
                                                                                    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229) 
                                                                                    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700) 
                                                                                    at android.os.Handler.handleCallback(Handler.java:733) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                                 Caused by: java.lang.NoSuchFieldError: ir.mirrajabi.persiancalendar.R$id.fragment_holder
                                                                                    at ir.mirrajabi.persiancalendar.PersianCalendarView.makeView(PersianCalendarView.java:103)
                                                                                    at ir.mirrajabi.persiancalendar.PersianCalendarView.<init>(PersianCalendarView.java:35)
                                                                                    at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:595) 
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                    at com.track.mansoorjafari.tracking.fragments.persianCalendar_fragment.onCreateView(persianCalendar_fragment.java:54) 
                                                                                    at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809) 
                                                                                    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322) 
                                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229) 
                                                                                    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700) 
                                                                                    at android.os.Handler.handleCallback(Handler.java:733) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by MansoorJafari** [comment]
لاگ هم گرفتن توی این خط از کتابخونه وارد ارور میشه

        m.beginTransaction().replace(id.fragment_holder, this.mCalendarFragment, CalendarFragment.class.getName()).commit();

خط ۸۷ کتابخونه

**Comment by mirrajabi** [comment]
الان دارم تست میکنم همه چی منطقی داره کار میکنه.
یه نمونه کدی بهم بده که این مشکل رو ایجاد کنه حداقل دستم بیاد داستان چیه.

**Comment by mirrajabi** [comment]
توی دیباگ پیش میاد این مشکل؟

**Comment by MansoorJafari** [comment]
من داخل فرگمنت قرار دادم این تقویم رو و با استفاده از کد زیر اجراش میکنم

`Fragment fragment = new persianCalendar_fragment();
            FragmentManager fragmentManager = getActivity().getSupportFragmentManager();
            fragmentManager.beginTransaction().add(R.id.content_frames, fragment).commit();`


نمونه کد خاص دیگه ای ندارم

خواستم ببینم مشکل از کجاست برنامه بردم تو حالت دیباگ بعدش دیدم خط ۸۷ کلاس PersianCalendarView ارور میده

**Comment by mirrajabi** [comment]
اونی که گفتی خط 103 هست نه 87
`m.beginTransaction().replace(id.fragment_holder, this.mCalendarFragment, CalendarFragment.class.getName()).commit();`
استاتیک ایمپورت شده R و
`id.fragment_holder` اینجا
[که توی این کتابخونه اینطوری نیست.](https://github.com/Roojin/persian-calendar-view/blob/435376770a6ef66a2ee1e27fb164f56a0db848e3/persiancalendar/src/main/java/ir/mirrajabi/persiancalendar/PersianCalendarView.java#L103)
مطمئنی داری از آخرین نسخه همین کتابخونه استفاده میکنی؟
پروگارد و اینا ستاپش روشنه؟ اگه هست ممکنه داستان سر اون باشه که اونم بعیده.
و اینکه این اتفاق تو حالت دیباگ پیش میاد یا بعد ساین کردن اِی پی کِی؟
نهایت چیزی که من از این توضیحات میتونم در بیارم اینه که یه بلایی سر این آیدی بیچاره اومده.

**Comment by MansoorJafari** [comment]
از همین که داخل این لینک  
https://github.com/Roojin/persian-calendar-view
گذاشتید دارم استفاده میکنم

من میگم توی اکتیوتی کاملا اوکیه
ولی توی فرگمنت مشکل داره

**Comment by mirrajabi** [comment]
با گریدل به پروژه اضافه کردی یا دستی؟

**Comment by MansoorJafari** [comment]
با گریدل

میخوام الان دستی تستش کنم

**Comment by mirrajabi** [comment]
فیکس شد؟
توی پروژه ی خالی تست کن اگه همین ارور رو داد کل پروژه رو برام ایمیل کن

**Comment by MansoorJafari** [comment]
خیر فیکس نشده 

توی پروژه خالی جواب میده 
ولی توی پروژه خودم این مورد اوکی نمیشه.

**Comment by MansoorJafari** [comment]
توی پروژم اصلا توی اکتیوتی هم نمیشه ستش کرد

کلا بااین پروژه مشکل داره فک کنم.

**Comment by mirrajabi** [comment]
مشکل بوجود اومده به این پروژه مربوط نمیشه.
ساختار پروژت رو بررسی کن.
اگه مطمئن شدی که مشکل ازاین پروژست دوباره بازش کن و دلیل منطقی بیار واسش.

**Comment by SirLordPouya** [comment]
سلام. منم دقیقا به همین مشکل خوردم.
وقتی که از نسخه ۱.۲.۱ توی فرگمنت استفاده میکنم  این مشکل پیش میاد.
چند خط آخری که به درد شما میخوره : 
```
 Caused by: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.support.v7.app.AppCompatActivity
 at ir.mirrajabi.persiancalendar.PersianCalendarView.makeView(PersianCalendarView.java:102)
 at ir.mirrajabi.persiancalendar.PersianCalendarView.<init>(PersianCalendarView.java:35)

```
